"""empty message

Revision ID: 09719d72cbef
Revises: 67006cf3e056
Create Date: 2020-03-11 12:13:49.647530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09719d72cbef'
down_revision = '67006cf3e056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_id'), table_name='review')
    # ### end Alembic commands ###
