"""empty message

Revision ID: 3897b6ed9cc8
Revises: 62f8ebd58b8d
Create Date: 2020-04-08 15:15:29.061831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3897b6ed9cc8'
down_revision = '62f8ebd58b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('num_of_reviews', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'num_of_reviews')
    # ### end Alembic commands ###
