"""empty message

Revision ID: 3e66be435552
Revises: 3897b6ed9cc8
Create Date: 2020-04-09 23:29:04.892546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e66be435552'
down_revision = '3897b6ed9cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('team')
    )
    op.add_column('user', sa.Column('team', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'team')
    op.drop_table('teams')
    # ### end Alembic commands ###
