"""empty message

Revision ID: 5d0e6f5ef076
Revises: 76c6f5308e54
Create Date: 2020-03-28 17:08:31.904719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0e6f5ef076'
down_revision = '76c6f5308e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('last_changed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'last_changed')
    # ### end Alembic commands ###
