"""empty message

Revision ID: a26981a29ae3
Revises: f24ddb65cfb2
Create Date: 2020-04-07 17:01:52.631146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26981a29ae3'
down_revision = 'f24ddb65cfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('tagString', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'tagString')
    # ### end Alembic commands ###
